name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings
    - name: test
      run: cargo test --verbose
    - name: build
      run: cargo build --release --verbose
